language: python
dist: focal
python:
    - 2.7
    - 3.6
    - 3.7
    - 3.8
    - pypy2
    - pypy3
install:
    - pip install coverage coveralls flake8 pytest
    - pip install .[test]
script:
    - coverage run -m pytest
    - flake8 src setup.py
after_success:
    - coveralls
    - coverage report -m --fail-under=100
notifications:
    email: false
